### ISSUE TITLE
the get rewards

### ISSUE THREAD

**Issue by awadeuwu22** [DavidBuchanan314/beatstar-tools#1]
How is the method of use of this file? For the printing of the link

**Comment by DavidBuchanan314** [comment]
`python3 get_rewards.py`

**Comment by awadeuwu22** [comment]
it worked, but it only open a python prompt and it closed a miliseconds after opening it, it didn't give me the link or something, do i have to do something before that?

**Comment by DavidBuchanan314** [comment]
Sounds like you need to run the command from a terminal window. I don't know how to do that, because I'm not a Windows user (which I assume you're using)
